version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: apcore-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - apcore-pgdata:/var/lib/postgresql/data
    networks:
      - apcore-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - apcore-network
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_HOST: postgres
      PG_PORT: 5432

volumes:
  apcore-pgdata:

networks:
  apcore-network: